version: '2.17.2'

services:
  redis:
    image: redis:latest
    container_name: db-redis-cache-subscriptions
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redisdata:/data

  db:
    image: postgres:latest
    container_name: db-postgres-subscriptions
    env_file:
      - postgres.env
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgressql/data

volumes:
  redisdata:
  pg-data:
